# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://capturethenarrative.com
title: Capture the Narrative Competition
email: hammond.pearce@unsw.edu.au
author: University of New South Wales
description: > # "Write an awesome description for your new site here. 
  Capture the Narrative is a competition that encourages participants to 
  explore how AI and LLMs can be used to manipulate discussions and perspectives
  on social media platforms.
  Participants will create bots that can generate content, engage in discussions,
  and influence narratives in a controlled environment, simulating real-world social media dynamics."
copyright: 'Copyright &copy; 2025 UNSW. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap
#   - title: linkedin
#     url: 
